import React from 'react';
import ReactDOM from 'react-dom/client';
/*
 *  Header
 *      - Logo
 *      - Navigation (Home, About Us, Contact Us, Cart)
 *  Body
 *     - Search bar
 *    - Restaurants List
 *  Footer
 *    - Social Media Links
 *    - Copyright
 *    - Address
 *
 */

const Header = () => {
  return (
    <header id="header">
      <img
        id="logo"
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzKb_ifO8E7BDZm1yu1N1pMqrgi_v9ctxzSA&s"
        alt="logo"
      />
      <div id="nav">
        <ul>
          <li className="list-items">Home</li>
          <li className="list-items">About Us</li>
          <li className="list-items">Contact Us</li>
          <li>
            <img
              id="cart"
              src="https://upload.wikimedia.org/wikipedia/commons/4/40/Shopping-cart-icon-with-bags-symbol-only.png"
              alt="cart"
            />
          </li>
        </ul>
      </div>
    </header>
  );
};

const Restaurantcard = (props) => {
  const { brand_name, banner_image_es, description, main_offering } =
    props?.restData;
  return (
    <div className="res-card">
      <img className="res-img" src={banner_image_es} alt="food image" />
      <h3>{brand_name}</h3>
      <p>{description}</p>
      <p>
        <strong>Specialty</strong>: {main_offering}
      </p>
    </div>
  );
};

const restList = [
  {
    brand_id: 20,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/ff45eb24-ff5d-49d5-8652-7f90aaee28f5.jpg',
    brand_name: 'Faasos',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Indulgent wraps loaded with high protein fillings',
    logo: 'https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg',
    main_offering: 'Wraps',
    slug: 'faasos',
    is_exclusive: 0,
    sequence: 0,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/125b377f-0b15-42a2-9775-18bc1dfc4f02.jpg',
  },
  {
    brand_id: 26,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/44df4975-8ff8-49dd-8e66-58d4d9a80a87.jpg',
    brand_name: 'Behrouz Biryani',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Handcrafted, Royal Biryanis',
    logo: 'https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg',
    main_offering: 'Royal Biryani',
    slug: 'behrouz-biryani',
    is_exclusive: 0,
    sequence: 1,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/eecae976-af37-4f0f-adfe-a5a68b401729.jpg',
  },
  {
    brand_id: 21,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/df8fad54-afab-4bfc-b6c8-5a6f64d2ef22.jpg',
    brand_name: 'Ovenstory',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Pizza with standout toppings',
    logo: 'https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg',
    main_offering: 'Pizzas',
    slug: 'ovenstory',
    is_exclusive: 0,
    sequence: 2,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/10de7f45-0c71-4dec-b530-6518668a79e8.jpg',
  },
  {
    brand_id: 23,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/dd79d385-5898-4956-8a07-718b8ddde9ff.jpg',
    brand_name: 'Firangi Bake',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Safe & Legendary Bakes',
    logo: 'https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/LEGFVYDHFK.jpeg',
    main_offering: 'Pasta & Lasagnas',
    slug: 'firangi-bake',
    is_exclusive: 0,
    sequence: 3,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/be6ab66f-c173-414c-889e-2600cac04268.jpg',
  },
  {
    brand_id: 24,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/e092f756-cac6-49f7-8ab6-4de3d167bdce.png',
    brand_name: 'Sweet Truth',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'The Purest Indulgence',
    logo: 'https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/2QK8YNKIWE.jpeg',
    main_offering: 'Desserts',
    slug: 'sweet-truth',
    is_exclusive: 0,
    sequence: 4,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/2d127bbd-8f26-41fb-9a78-9f37678dae26.png',
  },
  {
    brand_id: 30,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/a2963595-02b9-4472-80a5-e790d9308d93.jpg',
    brand_name: 'The Good Bowl',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Delicious Bowl Meals - Hygienic & Safe',
    logo: 'https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg',
    main_offering: 'Rice Bowl',
    slug: 'the-good-bowl',
    is_exclusive: 0,
    sequence: 5,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/233e155d-e498-4239-9013-7cb4c999d0ab.jpg',
  },
  {
    brand_id: 27,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/53994cc4-2afc-4e3a-9ff4-0af4c6e3a1da.jpg',
    brand_name: 'Lunchbox - Meals & Thalis',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Homestyle, Wholesome, Delightful',
    logo: 'https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/EA1BCMJCWN.jpeg',
    main_offering: 'Homestyle Meals',
    slug: 'lunchbox',
    is_exclusive: 0,
    sequence: 6,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/1b72edd0-d27c-4ca9-b9ad-6a050e7ed25b.jpg',
  },
  {
    brand_id: 51,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d4f6cedf-1e89-4aa5-a91d-8bb425a4f686.jpg',
    brand_name: 'Marrakesh',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Filled to the brim with Lebanese taste',
    logo: 'https://rp-media.faasos.io/catalog/images/YKPZYQC3RK.png',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/YKPZYQC3RK.png',
    background_url: 'https://rp-media.faasos.io/catalog/images/YKPZYQC3RK.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/YKPZYQC3RK.png',
    main_offering: 'Shawarma',
    slug: 'marrakesh',
    is_exclusive: 0,
    sequence: 6,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/d07e6cfd-044b-41f1-95c2-e662d37618e9.jpg',
  },
  {
    brand_id: 25,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/cbd4171c-dc9c-4ba4-96f8-ef4e4c3f959e.jpg',
    brand_name: 'The Biryani Life',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Hyderabad & Lucknow Biryani experts',
    logo: 'https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg',
    main_offering: 'Hyderabadi Biryani',
    slug: 'the-biryani-life',
    is_exclusive: 0,
    sequence: 7,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/a5157179-7451-48b1-8797-b63aac29573d.jpg',
  },
  {
    brand_id: 31,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/bf483b98-1d1c-4aa2-b0c2-43f5b2175bd7.jpg',
    brand_name: 'Veg Meals by LunchBox',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Satvik bhi, Delicious bhi',
    logo: 'https://rp-media.faasos.io/catalog/images/UQ4W3WVNYGOG.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/UQ4W3WVNYGOG.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/UQ4W3WVNYGOG.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/UQ4W3WVNYGOG.jpeg',
    main_offering: 'Veg Meals',
    slug: 'pure-veg-meals-by-lunchbox',
    is_exclusive: 0,
    sequence: 8,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/689f9d0b-f389-4fb3-8ff3-104fead5d9ac.jpg',
  },
  {
    brand_id: 47,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/92bd394e-fa7b-4470-8d79-732f9f5fdd4b.jpg',
    brand_name: 'Mad Over Donuts',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Bite into happiness',
    logo: 'https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png',
    background_url: 'https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png',
    main_offering: 'Donuts',
    slug: 'mad-over-donuts',
    is_exclusive: 0,
    sequence: 9,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/4d205101-2a4c-444d-a5bd-64b10cee4e51.jpg',
  },
  {
    brand_id: 57,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/3ad53104-ebcf-4d61-8f9a-9032f5abfc34.jpeg',
    brand_name: 'Natural Ice Cream',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'How real ice cream should be.',
    logo: 'https://rp-media.faasos.io/catalog/images/07HHDZHUW3.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/07HHDZHUW3.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/07HHDZHUW3.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/07HHDZHUW3.jpeg',
    main_offering: 'Ice Cream',
    slug: 'natural-ice-cream',
    is_exclusive: 0,
    sequence: 9,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/c3bc629f-9b54-47ea-b5c7-3340f0dbb879.png',
  },
  {
    brand_id: 55,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/dbd14ffe-3ef6-458a-b240-23b67fe3f79f.jpg',
    brand_name: 'The Brooklyn Creamery',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Guilt Free Indulgent Ice Creams',
    logo: 'https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png',
    background_url: 'https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/RIYENY8KQR.png',
    main_offering: 'Ice Cream',
    slug: 'the-brooklyn-creamery',
    is_exclusive: 0,
    sequence: 10,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/57981af2-15c0-4d9c-a39f-753500625017.jpg',
  },
  {
    brand_id: 61,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/fb2ff4ad-8a3d-409f-bc7a-74668ad0d40a.jpg',
    brand_name: 'Biryani Blues',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Its - Meri Wali Biryani',
    logo: 'https://rp-media.faasos.io/catalog/images/AFTS11RUBZ.png',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/AFTS11RUBZ.png',
    background_url: 'https://rp-media.faasos.io/catalog/images/AFTS11RUBZ.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/AFTS11RUBZ.png',
    main_offering: 'Biryani',
    slug: 'biryani-blues',
    is_exclusive: 0,
    sequence: 10,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/91428d9e-66c1-48fe-99d4-2fb657ec3422.png',
  },
  {
    brand_id: 56,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d7f5f1e3-9921-40b4-af98-886c229e96cf.jpg',
    brand_name: 'Zomoz',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Always Better Momos',
    logo: 'https://rp-media.faasos.io/catalog/images/ICH3R4LTJB.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/ICH3R4LTJB.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/ICH3R4LTJB.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/ICH3R4LTJB.jpeg',
    main_offering: 'Momos',
    slug: 'zomoz',
    is_exclusive: 0,
    sequence: 11,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/6e751824-8da3-4f5c-acbd-5bd0706ea53d.jpg',
  },
  {
    brand_id: 58,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/35469862-86bd-4bae-bf38-3d24e50e0a11.jpg',
    brand_name: 'The Belgian Waffle Co.',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'The Belgian Waffle Co.',
    logo: 'https://rp-media.faasos.io/catalog/images/EKPCVLHGZ4.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/EKPCVLHGZ4.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/EKPCVLHGZ4.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/EKPCVLHGZ4.jpeg',
    main_offering: 'Waffles',
    slug: 'the-belgian-waffle-co',
    is_exclusive: 0,
    sequence: 11,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/bd88aab5-8b32-4d02-9c19-dd60f5e6536c.jpg',
  },
  {
    brand_id: 121,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/1c96e2e7-742d-4b1a-a07d-83d45f273918.png',
    brand_name: 'Tea Post',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Tea Post',
    logo: 'https://rp-media.faasos.io/catalog/images/C1WT7HCQWR.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/C1WT7HCQWR.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/C1WT7HCQWR.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/C1WT7HCQWR.jpeg',
    main_offering: 'Beverage',
    slug: 'tea_post',
    is_exclusive: 0,
    sequence: 11,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/49c27122-efff-406a-bead-85bc0f5d1f8f.jpg',
  },
  {
    brand_id: 82,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d3268cfb-a448-4638-9b84-32b822bd9322.jpg',
    brand_name: "Faasos' Signature Wraps & Rolls",
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Extraordinarily Indulgent Wraps',
    logo: 'https://rp-media.faasos.io/catalog/images/DT0V7MWZUK.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/DT0V7MWZUK.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/DT0V7MWZUK.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/DT0V7MWZUK.jpeg',
    main_offering: 'Loaded wrap',
    slug: 'signature-wraps-rolls-by-faasos',
    is_exclusive: 0,
    sequence: 12,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/5d9d7626-e803-40b0-8b0b-62570e1b8ad0.jpg',
  },
  {
    brand_id: 62,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/8ef537f5-e21e-4fa3-ad3d-0cbc681074ab.jpeg',
    brand_name: 'Choko La',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/33MXUVNWJD.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/33MXUVNWJD.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/33MXUVNWJD.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/33MXUVNWJD.jpeg',
    main_offering: 'Cakes and Chocolates',
    slug: 'choko-la',
    is_exclusive: 0,
    sequence: 12,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/fa5b3a59-8e1e-4504-8043-42affcac3607.jpg',
  },
  {
    brand_id: 146,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/cc303d6c-68d7-4715-a764-bbd99aa4aa33.jpg',
    brand_name: 'Prasuma Momo Kitchen',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Impossibly Delicious Momos',
    logo: 'https://rp-media.faasos.io/catalog/images/HH7GJZX60G.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/HH7GJZX60G.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/HH7GJZX60G.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/HH7GJZX60G.jpeg',
    main_offering: 'Momos',
    slug: 'prasuma',
    is_exclusive: 0,
    sequence: 12,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/a6461d9f-40cd-485d-b580-74772eabb133.jpg',
  },
  {
    brand_id: 73,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/6584aea2-eedf-4016-8179-c5ed5e4abe11.jpg',
    brand_name: 'Veg Daawat by Behrouz',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'A curated spread of royal veg biryanis & kebabs',
    logo: 'https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/SV1VBOX1CM.jpeg',
    main_offering: 'Royal Biryani',
    slug: 'veg-daawat-by-behrouz',
    is_exclusive: 0,
    sequence: 12,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/e8a97c77-02a5-4060-94b1-e2be4e28acd8.jpg',
  },
  {
    brand_id: 93,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d758442b-293b-402c-9fef-c6325156a1ca.jpg',
    brand_name: 'Big Wong',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png',
    background_url: 'https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/IDKTEGMPGK.png',
    main_offering: 'Chinese',
    slug: 'big-wong',
    is_exclusive: 0,
    sequence: 12,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/ed5ae91c-b2a9-40ea-b3fd-1d8e82c74225.jpg',
  },
  {
    brand_id: 92,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/dcd48237-4194-4d8f-a7b8-b0c82ea98172.jpg',
    brand_name: 'Chinese Daily',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png',
    background_url: 'https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/MU2UAUHTE2.png',
    main_offering: 'Asian',
    slug: 'chinese-daily',
    is_exclusive: 0,
    sequence: 13,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/4959cb60-6330-488a-9041-13829e540685.jpg',
  },
  {
    brand_id: 50,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/c9ba5b8a-c85b-4816-b67c-7db0b03c1709.jpg',
    brand_name: 'Smoor',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Tastes as sublime as they look',
    logo: 'https://rp-media.faasos.io/catalog/images/MXMTI3Y8QA.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/MXMTI3Y8QA.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/MXMTI3Y8QA.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/MXMTI3Y8QA.jpeg',
    main_offering: 'Desserts',
    slug: 'smoor',
    is_exclusive: 0,
    sequence: 14,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/88f644de-350c-4b13-9c07-d27022551d68.jpg',
  },
  {
    brand_id: 170,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/06474ac3-719f-4ab4-a366-4f23888ad800.jpeg',
    brand_name: 'Paras Kulfi-100% Natural Ice Cream ',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Ice Cream',
    logo: 'https://rp-media.faasos.io/catalog/images/7GE9LVSBFBDS.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/7GE9LVSBFBDS.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/7GE9LVSBFBDS.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/7GE9LVSBFBDS.jpeg',
    main_offering: 'Ice Cream',
    slug: 'paras-kulfi-100-natural-indian-ice-cream',
    is_exclusive: 0,
    sequence: 14,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/abe16785-ba34-43df-b7e5-38662a8717b3.jpeg',
  },
  {
    brand_id: 158,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/e2b1b28b-8857-4964-82f3-425050f6da39.jpg',
    brand_name: 'DMB Sweets',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: '',
    logo: 'https://rp-media.faasos.io/catalog/images/IOJIYN5NXM2I.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/IOJIYN5NXM2I.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/IOJIYN5NXM2I.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/IOJIYN5NXM2I.jpeg',
    main_offering: 'Sweets',
    slug: 'dmb-sweets',
    is_exclusive: 0,
    sequence: 14,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/f131ac04-5195-4b91-b3f0-099f794a481e.jpg',
  },
  {
    brand_id: 166,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/dc72970b-21ea-4460-b1de-bc276e607a9a.jpg',
    brand_name: "Wendy's Flavor Fresh Burgers",
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description:
      'Craveworthy & indulging range of flavorful & fresh burgers, wraps & loaded fries',
    logo: 'https://rp-media.faasos.io/catalog/images/XSKSXK5TY60T.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/XSKSXK5TY60T.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/XSKSXK5TY60T.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/XSKSXK5TY60T.jpeg',
    main_offering: 'Burgers',
    slug: 'wendys-flavor-fresh-burgers',
    is_exclusive: 0,
    sequence: 15,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/e5dc5224-0bab-496f-bd73-1b4e2f29ba3b.jpg',
  },
  {
    brand_id: 147,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/1809d337-96f3-4207-b53e-0092a11a2131.png',
    brand_name: 'Baskin Robbins - Ice Creams',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Ice Cream That The World Loves',
    logo: 'https://rp-media.faasos.io/catalog/images/SLRYW2GDTO.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/SLRYW2GDTO.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/SLRYW2GDTO.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/SLRYW2GDTO.jpeg',
    main_offering: 'Ice Cream',
    slug: 'baskin-robbins',
    is_exclusive: 0,
    sequence: 16,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/1bc4b3d3-359f-42f3-a92a-d59369360802.jpg',
  },
  {
    brand_id: 176,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/4c6581c8-560b-49bc-bbf4-f3717aba07de.png',
    brand_name: 'Prasuma Momo Kitchen',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Impossibly Delicious Momos\n',
    logo: 'https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/MIEMPEV11DIV.jpeg',
    main_offering: 'Momos',
    slug: 'prasuma-momos',
    is_exclusive: 0,
    sequence: 16,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/8471bb13-e93b-4a79-803b-8de2f8318035.jpg',
  },
  {
    brand_id: 109,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d455c852-50f8-4a29-81ad-1c3f4b2f6a94.jpg',
    brand_name: 'Goodluck Cafe',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Irani Chai, Bun Maska & More',
    logo: 'https://rp-media.faasos.io/catalog/images/4QAJBT2HQF.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/4QAJBT2HQF.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/4QAJBT2HQF.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/4QAJBT2HQF.jpeg',
    main_offering: 'All day breakfast',
    slug: 'goodluck-cafe',
    is_exclusive: 0,
    sequence: 16,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/02ee2e33-32ef-47fc-b243-f4f0de074da9.jpg',
  },
  {
    brand_id: 88,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/c9447b30-f26f-4276-9969-a318a6475fc0.jpg',
    brand_name: 'Daryaganj',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/6GMK3HVC7C.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/6GMK3HVC7C.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/6GMK3HVC7C.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/6GMK3HVC7C.jpeg',
    main_offering: 'Mughlai',
    slug: 'daryaganj',
    is_exclusive: 0,
    sequence: 17,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/a4f66721-addd-4cc5-ab01-f9b3581622b4.jpg',
  },
  {
    brand_id: 179,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/8011cfe3-e9f6-49ba-889a-e355d123c3cd.jpg',
    brand_name: 'Kings Kulfi',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'Ice Cream',
    slug: 'kings-kulfi',
    is_exclusive: 0,
    sequence: 17,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/ff56241d-125d-4fed-99a7-0e998ccb3787.jpg',
  },
  {
    brand_id: 138,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/26a5b037-0b28-4939-a465-aa7fcdffffc3.jpg',
    brand_name: 'Mad Over Parathas & Pakodas',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Gourmet Parathas & Fusion Pakodas - Crazy Good Food!',
    main_offering: 'Parathas',
    slug: 'Mad Over Parathas - Pakodas',
    is_exclusive: 0,
    sequence: 17,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/6dc1c111-2d9c-47f7-93da-753e8b5ebf92.jpg',
  },
  {
    brand_id: 29,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/e65c0247-812f-43da-92b6-f156fc32e764.jpg',
    brand_name: "Wendy's Burgers",
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Stacked & packed for heavy duty',
    logo: 'https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg',
    main_offering: 'Burger',
    slug: 'wendy-s',
    is_exclusive: 0,
    sequence: 18,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/0f5f9749-d568-4b0d-a0a1-0d05717b3032.jpg',
  },
  {
    brand_id: 168,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/99f28b3c-d30e-4921-9277-30568911274e.jpg',
    brand_name: 'FRICKEN CHICKEN',
    brand_start_time: '11:00:00',
    brand_end_time: '03:00:00',
    description: 'Fried Chicken, Fast Food, Burgers, Sandwiches',
    logo: 'https://rp-media.faasos.io/catalog/images/23W63124TKHE.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/23W63124TKHE.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/23W63124TKHE.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/23W63124TKHE.jpeg',
    main_offering: 'Fried Chicken, Fast Food, Wings',
    slug: 'fricken',
    is_exclusive: 0,
    sequence: 18,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/0425daf5-2c7a-49e5-a716-c01d260d1408.jpg',
  },
  {
    brand_id: 153,
    client_source_id: 13,
    banner_image_es: '',
    brand_name: 'ITC Masterchef creations',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Food',
    main_offering: 'food',
    slug: 'itc-masterchef-creations',
    is_exclusive: 0,
    sequence: 18,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url: '',
  },
  {
    brand_id: 162,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/ef4272d1-ece0-4113-a83b-c8cea2c72b81.png',
    brand_name: 'Burgerama',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/WB4R5YJCCD27.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/WB4R5YJCCD27.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/WB4R5YJCCD27.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/WB4R5YJCCD27.jpeg',
    main_offering: 'burger',
    slug: 'burgerama',
    is_exclusive: 0,
    sequence: 18,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/e8754064-ac92-4aba-a6b1-478999324848.png',
  },
  {
    brand_id: 157,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/41cd960f-53c7-42fe-802e-95c8838d2aed.JPG',
    brand_name: "Auntie Fung's",
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Your Quintessential Asian Street Food',
    logo: 'https://rp-media.faasos.io/catalog/images/RAIWJSZOTSHZ.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/RAIWJSZOTSHZ.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/RAIWJSZOTSHZ.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/RAIWJSZOTSHZ.jpeg',
    main_offering: 'Pan Asian',
    slug: 'auntie-fungs',
    is_exclusive: 0,
    sequence: 18,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/79a57cd2-0c24-460b-b091-adefbc342798.jpeg',
  },
  {
    brand_id: 139,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/1e175d67-d5aa-4a68-bc9c-af5d08c830c2.jpg',
    brand_name: 'Mad Over Curry',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Authentic Curries of India!',
    main_offering: 'North Indian Food',
    slug: 'Mad-Over-Curry',
    is_exclusive: 0,
    sequence: 18,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/34bae5f3-c4bd-496e-9476-075419a5fbf4.jpg',
  },
  {
    brand_id: 196,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/ab8e8f36-373e-44e0-b102-b9d2c36f7519.jpg',
    brand_name: 'Shero Home Food',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'shero-home-food',
    is_exclusive: 0,
    sequence: 19,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/ebb74a27-ab49-4f7c-96bd-5d5c127bf701.jpg',
  },
  {
    brand_id: 140,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/cdf815e3-7191-48b1-bab2-4012447fc626.jpg',
    brand_name: 'Mealy - Your Everyday Meal',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Wholesome Everyday Meals.',
    main_offering: 'Thalis',
    slug: 'mealy-your-everyday-meal',
    is_exclusive: 0,
    sequence: 19,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/7efb85b6-de1b-4fe4-8eb3-3fcd99799853.jpg',
  },
  {
    brand_id: 175,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/8a747aa9-c5bb-4c4a-98fd-ae21ceb925fc.png',
    brand_name: 'Makhani Darbar',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Delicious Curries and Gravies',
    logo: 'https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg',
    main_offering: 'North Indian',
    slug: 'makhani-darbar',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/19989bb4-632b-45c8-a144-4e1ed7377fe3.jpg',
  },
  {
    brand_id: 200,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/1f1c486c-7a64-461a-bf11-ebb8ed54fcfc.jpg',
    brand_name: 'Cakes by Brownie Heaven',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/SBLPDP9XN3JH.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/SBLPDP9XN3JH.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/SBLPDP9XN3JH.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/SBLPDP9XN3JH.jpeg',
    main_offering: 'Desserts',
    slug: 'brownie-heaven',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/74d18d98-911a-4e94-996d-e835976794b5.jpg',
  },
  {
    brand_id: 197,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/50144f0b-072a-4fb5-8324-0dd518d23c12.jpg',
    brand_name: 'Shero Home Food Chettinad',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'shero-home-food-chettinad',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/6e9b4163-feb2-4391-aea3-6ef731f3b59d.jpg',
  },
  {
    brand_id: 53,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/26a234ab-729a-4a8c-98d5-de5fbcefe828.jpg',
    brand_name: 'Anand Sweets and Savouries',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Generations of sweet and savoury habits',
    logo: 'https://rp-media.faasos.io/catalog/images/5UYH4UVB4X.webp',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/5UYH4UVB4X.webp',
    background_url: 'https://rp-media.faasos.io/catalog/images/5UYH4UVB4X.webp',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/5UYH4UVB4X.webp',
    main_offering: 'Sweets',
    slug: 'anand-sweets',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/83444cca-f56c-494c-9b98-f0f590130f9d.png',
  },
  {
    brand_id: 191,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/f75b502b-3d59-4603-a6f6-c0f58b79d87a.jpg',
    brand_name: 'Plantaway',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'Ice cream',
    slug: 'plantaway',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/d736b5fd-a63b-46d7-85a5-d3e1b7a7bd58.jpg',
  },
  {
    brand_id: 185,
    client_source_id: 13,
    banner_image_es: '',
    brand_name: 'ITC Aashirvaad Soul Creations',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:59',
    description: 'Food',
    main_offering: '',
    slug: 'aashirwaad',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url: '',
  },
  {
    brand_id: 188,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/b190a488-58a0-42e8-b355-e2f45393cb57.jpg',
    brand_name: 'AbCoffee',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'Coffee',
    slug: 'ab-coffee',
    is_exclusive: 0,
    sequence: 20,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/0c627d79-3203-44c5-bad5-c3b50ea8c26d.jpg',
  },
  {
    brand_id: 183,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/4e670985-8ddd-4db9-902e-cd1f6274107c.jpg',
    brand_name: 'Go Zero - Guilt Free Ice Creams',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Ice Cream, Dessert\n',
    logo: 'https://rp-media.faasos.io/catalog/images/HZDLM9JM3DG1.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/HZDLM9JM3DG1.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/HZDLM9JM3DG1.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/HZDLM9JM3DG1.jpeg',
    main_offering: 'Ice Cream',
    slug: 'go-zero-guilt-free-ice-creams',
    is_exclusive: 0,
    sequence: 21,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/a7149a04-1ea0-487e-af5b-05055bf61ea1.jpg',
  },
  {
    brand_id: 198,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/5cf26c57-b220-43f8-a63e-366081373a48.jpg',
    brand_name: 'Shero Home Food Kerela',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'shero-home-food-kerela',
    is_exclusive: 0,
    sequence: 21,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/b7899537-3470-4a7f-89e1-b0f29f43180b.jpeg',
  },
  {
    brand_id: 182,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/38a959ac-8ed7-4847-9d36-31616952dbf1.jpg',
    brand_name: 'The Pizza Project',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Pizza Slices with standout toppings',
    logo: 'https://rp-media.faasos.io/catalog/images/Y97QPEXOAWRG.png',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/Y97QPEXOAWRG.png',
    background_url:
      'https://rp-media.faasos.io/catalog/images/Y97QPEXOAWRG.png',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/Y97QPEXOAWRG.png',
    main_offering: 'Pizza',
    slug: 'slice-it',
    is_exclusive: 0,
    sequence: 22,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/151f9afb-c0a7-4ee6-a68c-dc64f675b417.png',
  },
  {
    brand_id: 199,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/42e33695-cf77-4c75-91e0-8c7e61eb24d0.jpg',
    brand_name: 'Shero Home Food Andhra',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'shero-home-food-andhra',
    is_exclusive: 0,
    sequence: 22,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/4a9fefd5-df3e-4b83-8ab2-c10e45c299de.jpg',
  },
  {
    brand_id: 222,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/481ff087-2e49-48c7-926a-ed09bb7e14ad.png',
    brand_name: 'Parsi Dairy Farm',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/NGGLHO0TUYB8.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/NGGLHO0TUYB8.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/NGGLHO0TUYB8.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/NGGLHO0TUYB8.jpeg',
    main_offering: 'food',
    slug: 'parsi-dairy-farm',
    is_exclusive: 0,
    sequence: 22,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/192ab525-44fd-479c-8582-8fb98dc96666.png',
  },
  {
    brand_id: 163,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/6ccf49cb-ee1e-447a-b2d6-1b468b7d22d7.jpeg',
    brand_name: 'Ganesh Bhel',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:59',
    description: 'Street Food, Fast Food',
    logo: 'https://rp-media.faasos.io/catalog/images/QBWMCTMXGWN5.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/QBWMCTMXGWN5.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/QBWMCTMXGWN5.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/QBWMCTMXGWN5.jpeg',
    main_offering: 'Ganesh Bhel',
    slug: 'ganesh-bhel',
    is_exclusive: 0,
    sequence: 22,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/a21c5fa8-1ae5-4860-bfdd-0e34a8dd1f54.jpg',
  },
  {
    brand_id: 190,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/a004212c-8e29-4a1c-b632-bcfd19cf210c.jpeg',
    brand_name: 'Frozen Fun',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/ZWW4YN16MRN7.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/ZWW4YN16MRN7.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/ZWW4YN16MRN7.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/ZWW4YN16MRN7.jpeg',
    main_offering: 'Ice cream',
    slug: 'frozen-fun',
    is_exclusive: 0,
    sequence: 22,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/a49fd4df-c40f-4539-ae7f-7aaca453c83e.png',
  },
  {
    brand_id: 186,
    client_source_id: 13,
    banner_image_es: '',
    brand_name: 'ITC Sunfeast Baked Creations',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:59',
    description: 'Food',
    main_offering: '',
    slug: 'sunfeast-bakery',
    is_exclusive: 0,
    sequence: 22,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url: '',
  },
  {
    brand_id: 111,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/704985d8-4bd0-4433-99a9-551bc98feb1d.jpeg',
    brand_name: 'Kwality Walls Dessert and Ice Cream',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'A Treat For Every Occasion',
    logo: 'https://rp-media.faasos.io/catalog/images/U9JRLY6WJA.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/U9JRLY6WJA.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/U9JRLY6WJA.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/U9JRLY6WJA.jpeg',
    main_offering: 'Ice cream',
    slug: 'kwality-walls-frozen-dessert-and-ice-creme-shop-ae',
    is_exclusive: 0,
    sequence: 23,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/d3ba0f12-c05d-445d-a0ec-28929d1d6be2.jpg',
  },
  {
    brand_id: 211,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/59e2e86c-5c61-40aa-9355-5ae513c27e0f.jpg',
    brand_name: 'Rice Express by Shero',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/LIPIPLTFZ4XZ.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/LIPIPLTFZ4XZ.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/LIPIPLTFZ4XZ.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/LIPIPLTFZ4XZ.jpeg',
    main_offering: 'food',
    slug: 'rice-express-by-shero',
    is_exclusive: 0,
    sequence: 23,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/85766bdd-ec51-42f3-abd6-16273611e948.jpg',
  },
  {
    brand_id: 210,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/ee42716d-3c0c-494c-be44-4e1ef15cd2fa.jpg',
    brand_name: 'The Fresh Press',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'the-fresh-press',
    is_exclusive: 0,
    sequence: 23,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/71357852-3a50-47f5-9a0c-91dcca34d280.jpg',
  },
  {
    brand_id: 181,
    client_source_id: 13,
    banner_image_es: '',
    brand_name: 'EatSure Freebies',
    brand_start_time: '03:00:00',
    brand_end_time: '04:00:00',
    description: 'EatSure Freebies',
    main_offering: 'Freebie',
    slug: 'es-freebies',
    is_exclusive: 0,
    sequence: 24,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url: '',
  },
  {
    brand_id: 223,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d8c336f1-e83a-4988-a027-98356637be6a.jpg',
    brand_name: 'ES Cafe',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/AGJFCWKXYNKN.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/AGJFCWKXYNKN.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/AGJFCWKXYNKN.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/AGJFCWKXYNKN.jpeg',
    main_offering: 'food',
    slug: 'es-cafe',
    is_exclusive: 0,
    sequence: 24,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/1319bcc8-6ad4-48c8-86c1-335f816b907e.jpg',
  },
  {
    brand_id: 224,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/9b079183-a485-4c01-a76a-10ed546c5591.jpg',
    brand_name: 'Khoya',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'khoya',
    is_exclusive: 0,
    sequence: 24,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/8af82967-32f5-4add-b598-ef2c28e81ee8.jpg',
  },
  {
    brand_id: 159,
    client_source_id: 13,
    banner_image_es: '',
    brand_name: 'Gourmet Ice Cream Cakes by BR',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Gourmet Ice Cream Cakes by BR',
    main_offering: 'food',
    slug: 'gourmet-ice-cream-cakes-by-br',
    is_exclusive: 0,
    sequence: 24,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url: '',
  },
  {
    brand_id: 192,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/b9400e0d-8632-4a53-9fc3-3819f8c4cebd.jpg',
    brand_name: 'Slow Churn Ice Cream',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Ice cream',
    logo: 'https://rp-media.faasos.io/catalog/images/KQVLGODM00S1.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/KQVLGODM00S1.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/KQVLGODM00S1.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/KQVLGODM00S1.jpeg',
    main_offering: 'Ice Cream',
    slug: 'slow-churn-ice-cream',
    is_exclusive: 0,
    sequence: 25,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/bba8d7ef-ccb9-4a5b-8f26-446c4fd5c155.jpg',
  },
  {
    brand_id: 22,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/4f6cee66-4521-4c19-bdfb-1807962e9028.jpg',
    brand_name: 'Mandarin Oak',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description:
      'Chinese, Asian, Thai, Pan Asian, Fast Food, Fried Rice, Noodle',
    logo: 'https://rp-media.faasos.io/catalog/images/RWNLPLRLTW.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/RWNLPLRLTW.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/RWNLPLRLTW.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/RWNLPLRLTW.jpeg',
    main_offering: 'Chinese',
    slug: 'mandarin-oak',
    is_exclusive: 0,
    sequence: 25,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/9f53cfdb-abbc-4c2a-9c3c-c0f9e6722fec.jpg',
  },
  {
    brand_id: 209,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/1e182f1a-1db2-476b-9fd8-17e4df3b43be.jpeg',
    brand_name: 'Food Darzee',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/Z6GQTGRUPWLV.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/Z6GQTGRUPWLV.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/Z6GQTGRUPWLV.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/Z6GQTGRUPWLV.jpeg',
    main_offering: 'food',
    slug: 'food-darzee',
    is_exclusive: 0,
    sequence: 25,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/610bb928-cde4-455f-b835-c805e71999af.jpeg',
  },
  {
    brand_id: 218,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/add46bcc-4635-4ea4-8f02-770268c391cf.jpg',
    brand_name: 'Thalaiva Biryani',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg',
    main_offering: 'Biryani',
    slug: 'thalaiva-biryani',
    is_exclusive: 0,
    sequence: 26,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/d2092af7-4974-4b13-885b-60869eb2c505.jpeg',
  },
  {
    brand_id: 212,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/08cbb090-01b6-40eb-80d9-70c3b9f91f7d.jpg',
    brand_name: 'Taco Bell',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/V8BHANL9KDS8.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/V8BHANL9KDS8.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/V8BHANL9KDS8.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/V8BHANL9KDS8.jpeg',
    main_offering: 'food',
    slug: 'taco-bell',
    is_exclusive: 0,
    sequence: 26,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/2fc0f96e-d3a6-4cdb-94e3-e6589477882c.jpg',
  },
  {
    brand_id: 208,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/af695973-33e8-427f-a78d-b161ad8e33f4.jpg',
    brand_name: 'The Betel Leaf Co',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    main_offering: 'food',
    slug: 'the-betel-leaf-co',
    is_exclusive: 0,
    sequence: 26,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/7fc24acc-00ae-407c-be69-056f9354a41a.jpg',
  },
  {
    brand_id: 28,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/d6e0be21-aee6-4733-b27b-9c98f79b54cb.png',
    brand_name: 'Slay Coffee',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    description: 'Great Coffee. Everyday.',
    logo: 'https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg',
    rectangle_logo: 'https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg',
    background_url: 'https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/J5KTTXNSRL.jpeg',
    main_offering: 'Coffee',
    slug: 'slay-coffee',
    is_exclusive: 0,
    sequence: 27,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/f03f9411-45bd-47b4-a1f3-8fc795ce267b.jpg',
  },
  {
    brand_id: 219,
    client_source_id: 13,
    banner_image_es:
      'https://product-assets.faasos.io/eatsure_cms/production/5f7fbc85-ea82-4470-ae3b-957008fbaee6.jpg',
    brand_name: 'Rowdy Reddy Biryani',
    brand_start_time: '00:00:00',
    brand_end_time: '23:59:00',
    logo: 'https://rp-media.faasos.io/catalog/images/TCQ1D2V4HGKP.jpeg',
    rectangle_logo:
      'https://rp-media.faasos.io/catalog/images/TCQ1D2V4HGKP.jpeg',
    background_url:
      'https://rp-media.faasos.io/catalog/images/TCQ1D2V4HGKP.jpeg',
    background_url_large:
      'https://rp-media.faasos.io/catalog/images/TCQ1D2V4HGKP.jpeg',
    main_offering: 'food',
    slug: 'rowdy-reddy-biryani',
    is_exclusive: 0,
    sequence: 31,
    minimum_order_amount: 0,
    brand_delivery_fees: 0,
    max_delivery_time: 0,
    min_delivery_time: 0,
    inclusive_mrp: 1,
    is_opened: 0,
    discount_info: {},
    sure_points_multiplier_data: null,
    coupons_with_best_promotion: [{}],
    store_front_brand_image_url:
      'https://product-assets.faasos.io/eatsure_cms/production/3ab9ee5b-e09a-4470-93b4-e815c893cf60.jpg',
  },
];
const Body = () => {
  return (
    <div id="body">
      <div id="search">
        <input
          id="search-text"
          type="text"
          placeholder="Search for restaurants"
        />
        <button id="search-btn" type="submit">
          Search
        </button>
      </div>
      <div id="res-cards">
        {restList
          .filter(
            (rest) =>
              rest.banner_image_es != '' && rest.description?.length < 35
          )
          .map((rest) => (
            <Restaurantcard key={rest.brand_id} restData={rest} />
          ))}
      </div>
    </div>
  );
};
const App = () => {
  return (
    <div>
      <Header />
      <Body />
    </div>
    //Footer
  );
};

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);
